### login
POST http://localhost:3001/users/login
Content-Type: application/json

{
    "email": "jimmynarokian254@gmail.com",
    "password": "12345678"
   
}

### resetpwd
PUT http://localhost:3001/users/reset
Content-Type: application/json


{
    "email": "sunshine@gmail.com",
    "password": "12345678"
   
}
###Check details of the content

POST http://localhost:3001/users/checkdetails
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwNzMxNTg5LWMxZDQtNGY4NS1hNjA3LWUwYmM4OGNlYTk3YiIsImVtYWlsIjoiamltbXluYXJva2lhbjI1NEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDkzMjA5NzcsImV4cCI6MTcwOTQwNzM3N30.v8E9bggipEx3u9aSgNsy0x8Uhu9M-qPoH_X8E6CrGpk


