### login
POST http://localhost:3001/users/login
Content-Type: application/json

{
    "email": "jimmynarokian254@gmail.com",
    "password": "12345678"
   
}

### resetpwd
PUT http://localhost:3001/users/reset
Content-Type: application/json


{
    "email": "sunshine@gmail.com",
    "password": "12345678"
   
}
###Check details of the content

POST http://localhost:3001/users/checkdetails
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3YmQxYzAxLWUxZmUtNGNjYi04YmQxLTA3NDg0OGFhMGU2OCIsImVtYWlsIjoiamFtZXNrdzI2MDVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDc3ODk4ODIsImV4cCI6MTcwNzg3NjI4Mn0.-karkA_EBx8E6hLJDDPEtMjSjPnPsC7vjDe9V9_WYDc

