## Create Project
POST http://localhost:3001/projects
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkMTY0YzdiLTM4MDgtNDRmNy04ODAyLTZiNjIzZDQwMjE3MiIsImVtYWlsIjoic3Vuc2hpbmVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDc3MTk5ODMsImV4cCI6MTcwNzgwNjM4M30.aLeSja1Vdpw-yzbAzDBsnztimlPlKNMcP7HPMrmnoyU

{
    "projectname": "PMSNodeMailer",
    "description": "BackgroundService",
    "createdate": "2024-02-12",
    "enddate": "2024-12-31"
}

### Get all Projects
GET http://localhost:3001/projects
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkMTY0YzdiLTM4MDgtNDRmNy04ODAyLTZiNjIzZDQwMjE3MiIsImVtYWlsIjoic3Vuc2hpbmVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDc3MTk5ODMsImV4cCI6MTcwNzgwNjM4M30.aLeSja1Vdpw-yzbAzDBsnztimlPlKNMcP7HPMrmnoyU


### Get One
GET http://localhost:3001/projects/49ad4376-a194-4b79-b6b3-73aa82964aa2
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkMTY0YzdiLTM4MDgtNDRmNy04ODAyLTZiNjIzZDQwMjE3MiIsImVtYWlsIjoic3Vuc2hpbmVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDc3MDY4NDUsImV4cCI6MTcwNzcxMDQ0NX0.LNj6eEXUzLULN0g7yQLfB_OQrsYOvSYLEqDkh4eaDa4


### Update a user
PUT http://localhost:3001/projects/update/9bea87ed-1929-4963-b2c3-178839ef8b85
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkMTY0YzdiLTM4MDgtNDRmNy04ODAyLTZiNjIzZDQwMjE3MiIsImVtYWlsIjoic3Vuc2hpbmVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDc3MDY4NDUsImV4cCI6MTcwNzcxMDQ0NX0.LNj6eEXUzLULN0g7yQLfB_OQrsYOvSYLEqDkh4eaDa4


{
    "name": "Kariuki James",
    "email": "jameskw26@gmail.com",
    "role": "user",
    "password": "12345678",
    "areaofspecialization": "Software Engineer"
}

### Assign User

PUT http://localhost:3001/projects/assignuser/9bea87ed-1929-4963-b2c3-178839ef8b85
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkMTY0YzdiLTM4MDgtNDRmNy04ODAyLTZiNjIzZDQwMjE3MiIsImVtYWlsIjoic3Vuc2hpbmVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDc3MTk5ODMsImV4cCI6MTcwNzgwNjM4M30.aLeSja1Vdpw-yzbAzDBsnztimlPlKNMcP7HPMrmnoyU


{
    "user-id": "e9dbf2ce-f9ac-4fc2-bdca-ff"
}


### Delete a project

DELETE http://localhost:3001/projects/delete/9bea87ed-1929-4963-b2c3-178839ef8b85
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkMTY0YzdiLTM4MDgtNDRmNy04ODAyLTZiNjIzZDQwMjE3MiIsImVtYWlsIjoic3Vuc2hpbmVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDc3MDY4NDUsImV4cCI6MTcwNzcxMDQ0NX0.LNj6eEXUzLULN0g7yQLfB_OQrsYOvSYLEqDkh4eaDa4

